// GDS Graph Projections for Scientific Research
// Generated by create-context-graph
// Note: Requires Neo4j GDS plugin (AuraDS or Enterprise + GDS)

// Full entity projection (all node labels and relationship types)
CALL gds.graph.project(
  'scientific_research_full',
  ['Person', 'Organization', 'Location', 'Event', 'Object', 'Researcher', 'Paper', 'Dataset', 'Experiment', 'Grant', 'Institution'],
  ['WORKS_FOR', 'LOCATED_AT', 'PARTICIPATED_IN', 'AUTHORED', 'CITED', 'FUNDED_BY', 'REPLICATED', 'USED_DATASET', 'AFFILIATED_WITH', 'CONDUCTED', 'PRODUCED_DATASET']
);

// Community detection
CALL gds.louvain.write('scientific_research_full', {
  writeProperty: 'community'
});

// PageRank centrality
CALL gds.pageRank.write('scientific_research_full', {
  writeProperty: 'pagerank'
});

// FastRP embeddings for structural similarity
CALL gds.fastRP.write('scientific_research_full', {
  embeddingDimension: 128,
  writeProperty: 'fastrp_embedding'
});

// Clean up projection
CALL gds.graph.drop('scientific_research_full');
