// Schema for Scientific Research Context Graph
// Generated by create-context-graph

// Auto-generated schema for domain: Scientific Research
// Generated by create-context-graph

CREATE INDEX person_name IF NOT EXISTS FOR (n:Person) ON (n.name);

CREATE INDEX organization_name IF NOT EXISTS FOR (n:Organization) ON (n.name);

CREATE INDEX location_name IF NOT EXISTS FOR (n:Location) ON (n.name);

CREATE INDEX event_name IF NOT EXISTS FOR (n:Event) ON (n.name);

CREATE INDEX object_name IF NOT EXISTS FOR (n:Object) ON (n.name);

CREATE CONSTRAINT researcher_researcher_id_unique IF NOT EXISTS FOR (n:Researcher) REQUIRE n.researcher_id IS UNIQUE;
CREATE CONSTRAINT researcher_orcid_unique IF NOT EXISTS FOR (n:Researcher) REQUIRE n.orcid IS UNIQUE;
CREATE INDEX researcher_name IF NOT EXISTS FOR (n:Researcher) ON (n.name);

CREATE CONSTRAINT paper_doi_unique IF NOT EXISTS FOR (n:Paper) REQUIRE n.doi IS UNIQUE;
CREATE INDEX paper_name IF NOT EXISTS FOR (n:Paper) ON (n.name);

CREATE CONSTRAINT dataset_dataset_id_unique IF NOT EXISTS FOR (n:Dataset) REQUIRE n.dataset_id IS UNIQUE;
CREATE INDEX dataset_name IF NOT EXISTS FOR (n:Dataset) ON (n.name);

CREATE CONSTRAINT experiment_experiment_id_unique IF NOT EXISTS FOR (n:Experiment) REQUIRE n.experiment_id IS UNIQUE;
CREATE INDEX experiment_name IF NOT EXISTS FOR (n:Experiment) ON (n.name);

CREATE CONSTRAINT grant_grant_id_unique IF NOT EXISTS FOR (n:Grant) REQUIRE n.grant_id IS UNIQUE;
CREATE INDEX grant_name IF NOT EXISTS FOR (n:Grant) ON (n.name);

CREATE CONSTRAINT institution_institution_id_unique IF NOT EXISTS FOR (n:Institution) REQUIRE n.institution_id IS UNIQUE;
CREATE INDEX institution_name IF NOT EXISTS FOR (n:Institution) ON (n.name);

// Infrastructure: Document and Decision Trace indexes
CREATE INDEX document_title IF NOT EXISTS FOR (n:Document) ON (n.title);
CREATE INDEX document_template_id IF NOT EXISTS FOR (n:Document) ON (n.template_id);
CREATE CONSTRAINT decision_trace_id_unique IF NOT EXISTS FOR (n:DecisionTrace) REQUIRE n.id IS UNIQUE;

