/**
 * Domain configuration for Agent Memory
 * Generated by create-context-graph
 */

export const DOMAIN = {
  id: "agent-memory",
  name: "Agent Memory",
  description: "AI agent conversation tracking, entity extraction, memory management, and tool usage analysis",
  tagline: "AI-powered Agent Intelligence",
};

export const API_BASE = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000/api";

export const NODE_COLORS: Record<string, string> = {"Agent": "#8b5cf6", "Conversation": "#0ea5e9", "Entity": "#f59e0b", "Event": "#f97316", "Location": "#a855f7", "Memory": "#10b981", "Object": "#eab308", "Organization": "#64748b", "Person": "#22c55e", "Session": "#6366f1", "ToolCall": "#ef4444"};

export const NODE_SIZES: Record<string, number> = {"Agent": 30, "Conversation": 25, "Entity": 20, "Event": 20, "Location": 20, "Memory": 20, "Object": 20, "Organization": 20, "Person": 20, "Session": 25, "ToolCall": 15};

export const DEFAULT_CYPHER = `MATCH (a:Agent)-[r]-(n) RETURN a, r, n LIMIT 100`;

export const SCHEMA_NODE_SIZE = 30;
export const SCHEMA_REL_COLOR = "#94a3b8";

export interface GraphData {
  results: Record<string, unknown>[];
}

export interface DemoScenario {
  name: string;
  prompts: string[];
}

export const DEMO_SCENARIOS: DemoScenario[] = [{"name": "Literature Review", "prompts": ["Find the most cited papers in computational biology from the last 3 years", "What papers cite the landmark study on CRISPR gene editing by Doudna?", "Show me the citation network around deep learning in drug discovery"]}, {"name": "Research Management", "prompts": ["What grants are currently active and when do they expire?", "Show me all experiments that used the Genomics Benchmark dataset", "Which researchers at our institution have published in Nature?"]}, {"name": "Collaboration \u0026 Impact", "prompts": ["Find researchers working on similar topics to our lab\u0027s specialization", "What is the h-index distribution across our department?", "Which of our papers have been replicated by independent groups?"]}];
