/**
 * Domain configuration for Scientific Research
 * Generated by create-context-graph
 */

export const DOMAIN = {
  id: "scientific-research",
  name: "Scientific Research",
  description: "Research collaboration, publication tracking, grant management, and experiment analysis",
  tagline: "AI-powered Research Intelligence",
};

export const API_BASE = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8002/api";

export const NODE_COLORS: Record<string, string> = {"Dataset": "#0d9488", "Event": "#f97316", "Experiment": "#d97706", "Grant": "#16a34a", "Institution": "#6366f1", "Location": "#a855f7", "Object": "#eab308", "Organization": "#3b82f6", "Paper": "#be185d", "Person": "#22c55e", "Researcher": "#1d4ed8"};

export const NODE_SIZES: Record<string, number> = {"Dataset": 20, "Event": 20, "Experiment": 20, "Grant": 25, "Institution": 30, "Location": 20, "Object": 20, "Organization": 25, "Paper": 20, "Person": 20, "Researcher": 25};

export const DEFAULT_CYPHER = `MATCH (r:Researcher)-[:AUTHORED]->(p:Paper) RETURN r, p LIMIT 100`;

export const SCHEMA_NODE_SIZE = 30;
export const SCHEMA_REL_COLOR = "#94a3b8";

export interface GraphData {
  results: Record<string, unknown>[];
}

export interface DemoScenario {
  name: string;
  prompts: string[];
}

export const DEMO_SCENARIOS: DemoScenario[] = [{"name": "Literature Review", "prompts": ["Find the most cited papers in computational biology from the last 3 years", "What papers cite the landmark study on CRISPR gene editing by Doudna?", "Show me the citation network around deep learning in drug discovery"]}, {"name": "Research Management", "prompts": ["What grants are currently active and when do they expire?", "Show me all experiments that used the Genomics Benchmark dataset", "Which researchers at our institution have published in Nature?"]}, {"name": "Collaboration \u0026 Impact", "prompts": ["Find researchers working on similar topics to our lab\u0027s specialization", "What is the h-index distribution across our department?", "Which of our papers have been replicated by independent groups?"]}];
